// import { faker } from '@faker-js/faker';
// import fs from 'node:fs';
// import { json } from 'node:stream/consumers';

// function readCSV(csvFilePath) {
//   return new Promise((resolve, reject) => {
//     fs.readFile(csvFilePath, 'utf-8', (err, data) => {
//       if (err) {
//         reject(err);
//         return;
//       }

//       const lines = data.split('\n');
//       const headers = lines[0].split(',');
//       const jsonData = [];

//       for (let i = 1; i < lines.length; i++) {
//         const values = lines[i].split(',');
//         const row = {};

//         for (let j = 0; j < headers.length; j++) {
//           // 1. Remove white spaces
//           let value = values[j]?.trim();

//           // 2. Remove non-printable characters
//           // value = value?.replace(/[^\x20-\x7E]/g, '');

//           // 3. Strip non-numeric characters from phone fields
//           if (headers[j]?.includes('phone') || headers[j]?.includes('Phone')) {
//             value = value?.replace(/[^0-9]/g, '');
//           }

//           row[headers[j]] = value;
//         }
//         jsonData.push(row);
//       }

//       resolve(jsonData);
//     });
//   });
// }

// function writeToCSV(path, data) {
//   // Write CSV string to a new file
//   fs.writeFile(path, data, err => {
//     if (err) {
//       console.error('Error writing CSV file:', err);
//     } else {
//       console.log('CSV file written successfully!');
//     }
//   });
// }

// const path = 'PalstDB.csv';
// readCSV(path).then(data => {
//   writeToCSV('./userJSONData.txt', JSON.stringify(data));
//   console.log();
// });

export const plastunData = [
  {
    username: 'vaskivandriana',
    plastId: '6809',
    firstName: 'Andriana',
    lastName: 'Vaskiv',
    childFirstNameUa: 'Андріяна',
    childLastNameUa: 'Васьків',
    dob: '02/09/2005',
    stupin: 'Старша Пластунка',
    ulad: '',
    email: 'rvaskiv@gmail.com',
    phoneNumber: '6315268730',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '50 Paprocki Avenue',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Roman',
    parent1LastName: 'Vaskiv',
    parent1Email: 'rvaskiv@gmail.com',
    parent1PhoneNumber: '6315268730',
    parent2FirstName: 'Oksana',
    parent2LastName: 'Rybak',
    parent2Email: 'oksanarybak2@gmail.com',
    parent2PhoneNumber: '6315268731',
  },
  {
    username: 'podolskaemily',
    plastId: '6811',
    firstName: 'Emily',
    lastName: 'Podolska',
    childFirstNameUa: 'Емілі',
    childLastNameUa: 'Подольська',
    dob: '9/4/2007',
    stupin: 'Ю2',
    ulad: '',
    email: 'emily.podolska@gmail.com',
    phoneNumber: '6312157311',
    uaSchooGrade: '',
    usSchooGrade: '12',
    adressStreet: '350 Garden St',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Svyatoslav',
    parent1LastName: 'Podolskiy',
    parent1Email: 's_podolskiy@live.com',
    parent1PhoneNumber: '6315592506',
    parent2FirstName: 'Yevheniya',
    parent2LastName: 'Podolska',
    parent2Email: 'jane.podolska@gmail.com',
    parent2PhoneNumber: '6317049527',
  },
  {
    username: 'geretaviktoriia',
    plastId: '6812',
    firstName: 'Viktoriia',
    lastName: 'Gereta',
    childFirstNameUa: 'Вікторія',
    childLastNameUa: 'Герета',
    dob: '07/22/2006',
    stupin: 'Старша Пластунка',
    ulad: '',
    email: 'victoriagereta@gmail.com',
    phoneNumber: '6317413833',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '294 30th Street',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: 'Volymyr',
    parent1LastName: 'Gereta',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Iryna',
    parent2LastName: 'Gereta',
    parent2Email: 'vovtchyk@aol.com',
    parent2PhoneNumber: '6317421991',
  },
  {
    username: 'rybakpeter',
    plastId: '6814',
    firstName: 'Peter',
    lastName: 'Rybak',
    childFirstNameUa: 'Петро',
    childLastNameUa: 'Рибак',
    dob: '12/12/2007',
    stupin: 'Ю2',
    ulad: '',
    email: 'peterrybak1212@gmail.com',
    phoneNumber: '6315529880',
    uaSchooGrade: '',
    usSchooGrade: '11',
    adressStreet: '60 Seafield ln',
    adressTown: 'Bayshore',
    adressZipcode: '11706',
    adressState: 'NY',
    parent1FirstName: 'Ivan',
    parent1LastName: 'Rybak',
    parent1Email: '',
    parent1PhoneNumber: '6316816631',
    parent2FirstName: 'Ruslana',
    parent2LastName: 'Rybak',
    parent2Email: '',
    parent2PhoneNumber: '6316816627',
  },
  {
    username: 'podolskanicole',
    plastId: '6815',
    firstName: 'Nicole',
    lastName: 'Podolska',
    childFirstNameUa: 'Ніколь',
    childLastNameUa: 'Подольська',
    dob: '12/8/2009',
    stupin: 'Розвідувачка',
    ulad: '',
    email: 'nicole.podolska@icloud.com',
    phoneNumber: '6314826020',
    uaSchooGrade: '',
    usSchooGrade: '10',
    adressStreet: '350 Garden St',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Svyatoslav',
    parent1LastName: 'Podolskiy',
    parent1Email: 's_podolskiy@live.com',
    parent1PhoneNumber: '6315592506',
    parent2FirstName: 'Yevheniya',
    parent2LastName: 'Podolska',
    parent2Email: 'jane.podolska@gmail.com',
    parent2PhoneNumber: '6317049527',
  },
  {
    username: 'geretaelizabeth',
    plastId: '6816',
    firstName: 'Elizabeth',
    lastName: 'Gereta',
    childFirstNameUa: 'Елізабет',
    childLastNameUa: 'Герета',
    dob: '6/24/2009',
    stupin: 'Розвідувачка',
    ulad: '',
    email: 'elizabethgereta@gmail.com',
    phoneNumber: '6317472960',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '294 30th Street',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: 'Volymyr',
    parent1LastName: 'Gereta',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Iryna',
    parent2LastName: 'Gereta',
    parent2Email: 'vovtchyk@aol.com',
    parent2PhoneNumber: '6317421991',
  },
  {
    username: 'tsymbalistyyvyacheslav',
    plastId: '6817',
    firstName: 'Vyacheslav',
    lastName: 'Tsymbalistyy',
    childFirstNameUa: "В'ячеслав",
    childLastNameUa: 'Цимбаліста',
    dob: '6/14/2010',
    stupin: 'Учасник2',
    ulad: '',
    email: 'ruslana84.rt@gmail.com',
    phoneNumber: '6315758249',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '329 Kurzon Rd',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Andriy',
    parent1LastName: 'Tsymbalistyy',
    parent1Email: '',
    parent1PhoneNumber: '6314081911',
    parent2FirstName: 'Ruslana',
    parent2LastName: 'Tsymbalista',
    parent2Email: 'Ruslana84.rt@gmail.com',
    parent2PhoneNumber: '6315758249',
  },
  {
    username: 'popovichichristina',
    plastId: '6819',
    firstName: 'Christina',
    lastName: 'Popovichi',
    childFirstNameUa: 'Христина',
    childLastNameUa: 'Попович',
    dob: '08/01/2008',
    stupin: 'Ю2',
    ulad: '',
    email: 'SaraChristina55321@gmail.com',
    phoneNumber: '6318770038',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '225 N 4th Street',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'bibasophiya',
    plastId: '7003',
    firstName: 'Sophiya',
    lastName: 'Biba',
    childFirstNameUa: 'Софія',
    childLastNameUa: 'Біба',
    dob: '8/2/2010',
    stupin: 'Розвідувачка',
    ulad: '',
    email: 'sofbiba10@gmail.com',
    phoneNumber: '6313553033',
    uaSchooGrade: '9',
    usSchooGrade: '9',
    adressStreet: '1037 North Monroe Ave',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Iryna',
    parent2LastName: 'Biba',
    parent2Email: 'irynabiba@gmail.com',
    parent2PhoneNumber: '6313552266',
  },
  {
    username: 'hulamariya',
    plastId: '7004',
    firstName: 'Mariya',
    lastName: 'Hula',
    childFirstNameUa: 'Марія',
    childLastNameUa: 'Гула',
    dob: '1/8/2009',
    stupin: 'Розвідувачка',
    ulad: '',
    email: 'mariyahula8@icloud.com',
    phoneNumber: '6318560657',
    uaSchooGrade: '10',
    usSchooGrade: '10',
    adressStreet: '"28 Chassyl road',
    adressTown: '"',
    adressZipcode: 'Commack',
    adressState: '11725',
    parent1FirstName: 'NY',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: 'Maria',
    parent2Email: 'Hula',
    parent2PhoneNumber: '',
  },
  {
    username: 'hulasophiya',
    plastId: '7005',
    firstName: 'Sophiya',
    lastName: 'Hula',
    childFirstNameUa: 'Софія',
    childLastNameUa: 'Гула',
    dob: '5/11/2010',
    stupin: 'Розвідувачка',
    ulad: '',
    email: 'sophiahula11@icloud.com',
    phoneNumber: '6313576746',
    uaSchooGrade: '9',
    usSchooGrade: '9',
    adressStreet: '"28 Chassyl road',
    adressTown: '"',
    adressZipcode: 'Commack',
    adressState: '11725',
    parent1FirstName: 'NY',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'rybakeva',
    plastId: '7210',
    firstName: 'Eva',
    lastName: 'Rybak',
    childFirstNameUa: 'Ева',
    childLastNameUa: 'Рибак',
    dob: '4/21/2012',
    stupin: 'Учасник1',
    ulad: '',
    email: 'ruslanadubrovska@hotmail.com',
    phoneNumber: '6316816627',
    uaSchooGrade: '',
    usSchooGrade: '6',
    adressStreet: '60 Seafield ln',
    adressTown: 'Bayshore',
    adressZipcode: '11706',
    adressState: 'NY',
    parent1FirstName: 'Ivan',
    parent1LastName: 'Rybak',
    parent1Email: '',
    parent1PhoneNumber: '6316816631',
    parent2FirstName: 'Ruslana',
    parent2LastName: 'Rybak',
    parent2Email: '',
    parent2PhoneNumber: '6316816627',
  },
  {
    username: 'vaskivsofiya',
    plastId: '7369',
    firstName: 'Sofiya',
    lastName: 'Vaskiv',
    childFirstNameUa: 'Софія',
    childLastNameUa: 'Васьків',
    dob: '12/25/2013',
    stupin: '',
    ulad: '',
    email: 'rvaskiv@gmail.com',
    phoneNumber: '6315268730',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '50 Paprocki Avenue',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Roman',
    parent1LastName: 'Vaskiv',
    parent1Email: 'rvaskiv@gmail.com',
    parent1PhoneNumber: '6315268730',
    parent2FirstName: 'Oksana',
    parent2LastName: 'Rybak',
    parent2Email: 'oksanarybak2@gmail.com',
    parent2PhoneNumber: '6315268731',
  },
  {
    username: 'geretachristina',
    plastId: '7370',
    firstName: 'Christina',
    lastName: 'Gereta',
    childFirstNameUa: 'Христина',
    childLastNameUa: 'Герета',
    dob: '5/24/2012',
    stupin: 'Учасник1',
    ulad: '',
    email: 'vovtchyk@aol.com',
    phoneNumber: '6317421991',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '294 30th Street',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: 'Volymyr',
    parent1LastName: 'Gereta',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Iryna',
    parent2LastName: 'Gereta',
    parent2Email: 'vovtchyk@aol.com',
    parent2PhoneNumber: '6317421991',
  },
  {
    username: 'kolpynskyilukian',
    plastId: '7371',
    firstName: 'Lukian',
    lastName: 'Kolpynskyi',
    childFirstNameUa: 'Лукян',
    childLastNameUa: 'Коплинський',
    dob: '4/22/2009',
    stupin: 'Розвідувач',
    ulad: '',
    email: 'lukas220409@gmail.com',
    phoneNumber: '6316127410',
    uaSchooGrade: '',
    usSchooGrade: '10',
    adressStreet: '102 Boulevard ave',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'tsymbalistadiana',
    plastId: '7450',
    firstName: 'Diana',
    lastName: 'Tsymbalista',
    childFirstNameUa: 'Діяна',
    childLastNameUa: 'Цимбаліста',
    dob: '09/14/2015',
    stupin: '',
    ulad: '',
    email: 'ruslana84.rt@gmail.com',
    phoneNumber: '6315758249',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '329 Kurzon Rd',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Andriy',
    parent1LastName: 'Tsymbalistyy',
    parent1Email: '',
    parent1PhoneNumber: '6314081911',
    parent2FirstName: 'Ruslana',
    parent2LastName: 'Tsymbalista',
    parent2Email: 'Ruslana84.rt@gmail.com',
    parent2PhoneNumber: '6315758249',
  },
  {
    username: 'kosmenkodenis',
    plastId: '7856',
    firstName: 'Denis',
    lastName: 'Kosmenko',
    childFirstNameUa: 'Косменко',
    childLastNameUa: 'Денис',
    dob: '12/6/2013',
    stupin: '',
    ulad: '',
    email: 'innush26@gmail.com',
    phoneNumber: '6317037570',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '425 East Hoffman Ave',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: 'Ivan',
    parent1LastName: 'Kosmenko',
    parent1Email: 'kosmenkoivan@gmail.com',
    parent1PhoneNumber: '6317037570',
    parent2FirstName: 'Inna',
    parent2LastName: 'Kosmenko',
    parent2Email: 'innush26@gmail.com',
    parent2PhoneNumber: '6318716952',
  },
  {
    username: 'vasylyukstella',
    plastId: '7857',
    firstName: 'Stella',
    lastName: 'Vasylyuk',
    childFirstNameUa: 'Стелла',
    childLastNameUa: 'Василюк',
    dob: '12/18/2015',
    stupin: '',
    ulad: '',
    email: 'allan0086@yahoo.com',
    phoneNumber: '6315758249',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '',
    adressTown: '',
    adressZipcode: '',
    adressState: '',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'vasylevskaevelina',
    plastId: '7858',
    firstName: 'Evelina',
    lastName: 'Vasylevska',
    childFirstNameUa: 'Евеліна',
    childLastNameUa: 'Василевська',
    dob: '10/24/2015',
    stupin: '',
    ulad: '',
    email: 'vikavasylevska26@gmail.com',
    phoneNumber: '6315249184',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '112 South High Street',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: 'Stanislav',
    parent1LastName: 'Vasylevsky',
    parent1Email: '',
    parent1PhoneNumber: '6319442947',
    parent2FirstName: 'Victoriia',
    parent2LastName: 'Vasylevska',
    parent2Email: 'vikavasylevska26@gmail.com',
    parent2PhoneNumber: '6315249184',
  },
  {
    username: 'stelmakhyaroslav',
    plastId: '7859',
    firstName: 'Yaroslav',
    lastName: 'Stelmakh',
    childFirstNameUa: 'Ярослав',
    childLastNameUa: 'Стельмах',
    dob: '09/15/2013',
    stupin: '',
    ulad: '',
    email: 'mariana.shavitsa@gmail.com',
    phoneNumber: '6315724848',
    uaSchooGrade: '',
    usSchooGrade: '5',
    adressStreet: '34 Wood Place',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Mariana',
    parent2LastName: 'Shavitsa',
    parent2Email: 'mariana.shavitsa@gmail.com',
    parent2PhoneNumber: '6315724848',
  },
  {
    username: 'hrynyukemilia',
    plastId: '7860',
    firstName: 'Emilia',
    lastName: 'Hrynyuk',
    childFirstNameUa: 'Емілія',
    childLastNameUa: 'Гринюк',
    dob: '10/02/2015',
    stupin: '',
    ulad: '',
    email: 'Vhrynyuk@gmail.com',
    phoneNumber: '6313384738',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '74 Roslyn St',
    adressTown: 'Islip Terrace',
    adressZipcode: '11752',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'hrynyukjulia',
    plastId: '7861',
    firstName: 'Julia',
    lastName: 'Hrynyuk',
    childFirstNameUa: 'Юлія',
    childLastNameUa: 'Гринюк',
    dob: '12/6/2011',
    stupin: 'Учасник1',
    ulad: '',
    email: 'Vhrynyuk@gmail.com',
    phoneNumber: '6313384738',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '74 Roslyn St',
    adressTown: 'Islip Terrace',
    adressZipcode: '11752',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'hoyviktoriia',
    plastId: '7863',
    firstName: 'Viktoriia',
    lastName: 'Hoy',
    childFirstNameUa: 'Вікторія',
    childLastNameUa: 'Гой',
    dob: '04/11/2014',
    stupin: '',
    ulad: '',
    email: 'olenahoy1@gmail.com',
    phoneNumber: '6315535384',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '20 Ferndale Ct.',
    adressTown: 'Copiague',
    adressZipcode: '11726',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Olena',
    parent2LastName: 'Hoy',
    parent2Email: 'Olenahoy1@gmail.com',
    parent2PhoneNumber: '6315535384',
  },
  {
    username: 'vaskivroman',
    plastId: '8078',
    firstName: 'Roman',
    lastName: 'Vaskiv',
    childFirstNameUa: 'Роман',
    childLastNameUa: 'Васьків',
    dob: '01/28/1979',
    stupin: 'пластун сеньор',
    ulad: '',
    email: 'rvaskiv@gmail.com',
    phoneNumber: '6315268730',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '50 Paprocki Avenue',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'geretairyna',
    plastId: '8079',
    firstName: 'Iryna',
    lastName: 'Gereta',
    childFirstNameUa: 'Ірина',
    childLastNameUa: 'Герета',
    dob: '07/22/1978',
    stupin: 'пластунка сеньор',
    ulad: '',
    email: 'irynagereta@gmail.com',
    phoneNumber: '6317421991',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '294 30th Street',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'podolskiyyeheniya',
    plastId: '8080',
    firstName: 'Yeheniya',
    lastName: 'Podolskiy',
    childFirstNameUa: 'Євгенія',
    childLastNameUa: 'Подольська',
    dob: '11/19/1985',
    stupin: 'пластунка сеньор',
    ulad: '',
    email: 'jane.podolska@gmail.com',
    phoneNumber: '6317049527',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '350 Garden St',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'rybakoksana',
    plastId: '8081',
    firstName: 'Oksana',
    lastName: 'Rybak',
    childFirstNameUa: 'Оксана',
    childLastNameUa: 'Рибак',
    dob: '06/17/1975',
    stupin: 'пластунка сеньор',
    ulad: '',
    email: 'oksanarybak2@gmail.com',
    phoneNumber: '6315268731',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '50 Paprocki Avenue',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'tsymbalistaruslana',
    plastId: '8268',
    firstName: 'Ruslana',
    lastName: 'Tsymbalista',
    childFirstNameUa: 'Руслана',
    childLastNameUa: 'Цимбаліста',
    dob: '04/25/1984',
    stupin: 'пластунка сеньор',
    ulad: '',
    email: 'Ruslana84.rt@gmail.com',
    phoneNumber: '6315758249',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '329 Kurzon Road',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'kolpynskanadia',
    plastId: '',
    firstName: 'Nadia',
    lastName: 'Kolpynska',
    childFirstNameUa: 'Надія',
    childLastNameUa: 'Колпинська',
    dob: '02/16/2018',
    stupin: 'пластунка сеньор',
    ulad: '',
    email: 'kolpinska@gmail.com',
    phoneNumber: '6316217406',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '102 Boulevard ave',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  {
    username: 'koteckristian',
    plastId: '',
    firstName: 'Kristian',
    lastName: 'Kotec',
    childFirstNameUa: 'Христин',
    childLastNameUa: 'Котек',
    dob: '4/12/2015',
    stupin: '',
    ulad: '',
    email: 'Nsorych@gmail.com',
    phoneNumber: '6318771395',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '4 Greenbriar Ct.',
    adressTown: 'Holtsville',
    adressZipcode: '11742',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Nadiya',
    parent2LastName: 'Sorych',
    parent2Email: 'Nsorych@gmail.com',
    parent2PhoneNumber: '6318771395',
  },
  {
    username: 'kryvairyna',
    plastId: '',
    firstName: 'Iryna',
    lastName: 'Kryva',
    childFirstNameUa: 'Крива',
    childLastNameUa: 'Ірина',
    dob: '10/30/2014',
    stupin: '',
    ulad: '',
    email: 'kryvamariia41@gmail.com',
    phoneNumber: '5169289378',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '8576 Monroe Ave',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Mariia',
    parent2LastName: 'Kryva',
    parent2Email: 'kryvamariia41@gmail.com',
    parent2PhoneNumber: '5169289378',
  },
  {
    username: 'kytsaniukveronika',
    plastId: '',
    firstName: 'Veronika',
    lastName: 'Kytsaniuk',
    childFirstNameUa: 'Вероніка',
    childLastNameUa: 'Кицанюк',
    dob: '11/4/2014',
    stupin: '',
    ulad: '',
    email: 'lydmula19881411@gmail.com',
    phoneNumber: '16318387913',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '8517 North Monroe ave',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: 'Vitalii',
    parent1LastName: 'Kytsaniuk',
    parent1Email: 'kytsanykrobota@gmail.com',
    parent1PhoneNumber: '16318384729',
    parent2FirstName: '',
    parent2LastName: 'Kytsaniuk',
    parent2Email: 'lydmula19881411@gmail.com',
    parent2PhoneNumber: '16318387913',
  },
  {
    username: 'minzhosayeva',
    plastId: '',
    firstName: 'Yeva',
    lastName: 'Minzhosa',
    childFirstNameUa: 'Єва',
    childLastNameUa: 'Мінжоса',
    dob: '7/12/2011',
    stupin: 'Учасник2',
    ulad: '',
    email: 'minzhosa25@gmail.com',
    phoneNumber: '9342128529',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '162 Boulevard Ave',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Volodymyr',
    parent1LastName: 'Minzhosa',
    parent1Email: '',
    parent1PhoneNumber: '9342120561',
    parent2FirstName: 'Svitlana',
    parent2LastName: 'Minzhosa',
    parent2Email: 'minzhosa25@gmail.com',
    parent2PhoneNumber: '6319436146',
  },
  {
    username: 'minzhosaadam',
    plastId: '',
    firstName: 'Adam',
    lastName: 'Minzhosa',
    childFirstNameUa: 'Адам',
    childLastNameUa: 'Мінжоса',
    dob: '5/7/2016',
    stupin: '',
    ulad: '',
    email: 'minzhosa25@gmail.com',
    phoneNumber: '6319436146',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '162 Boulevard Ave',
    adressTown: 'West Islip',
    adressZipcode: '11795',
    adressState: 'NY',
    parent1FirstName: 'Volodymyr',
    parent1LastName: 'Minzhosa',
    parent1Email: '',
    parent1PhoneNumber: '9342120561',
    parent2FirstName: 'Svitlana',
    parent2LastName: 'Minzhosa',
    parent2Email: 'minzhosa25@gmail.com',
    parent2PhoneNumber: '6319436146',
  },
  {
    username: 'popovychmatthew',
    plastId: '',
    firstName: 'Matthew',
    lastName: 'Popovych',
    childFirstNameUa: 'Матвій',
    childLastNameUa: 'Попович',
    dob: '03/12/2014',
    stupin: '',
    ulad: '',
    email: 'vira487@gmail.com',
    phoneNumber: '6317477734',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '8509 N Monroe Ave',
    adressTown: 'Lindenhurst',
    adressZipcode: '11757',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: 'Vira',
    parent2LastName: 'Popovych',
    parent2Email: 'vira487@gmail.com',
    parent2PhoneNumber: '6317477734',
  },
  {
    username: 'vasurkovadym',
    plastId: '',
    firstName: 'Vadym',
    lastName: 'Vasurko',
    childFirstNameUa: 'Вадим',
    childLastNameUa: 'Васюрко',
    dob: '3/13/2012',
    stupin: 'Учасник 1',
    ulad: '',
    email: 'vadim.vasiurko@gmail.com',
    phoneNumber: '6316442497',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '"801 N Clinton Ave',
    adressTown: '"',
    adressZipcode: 'Lindenhurst',
    adressState: '11757',
    parent1FirstName: 'NY',
    parent1LastName: 'Petro',
    parent1Email: 'Vasiurko',
    parent1PhoneNumber: '',
    parent2FirstName: '6316446250',
    parent2LastName: 'Roksolana',
    parent2Email: 'Vasiurko',
    parent2PhoneNumber: '',
  },
  {
    username: 'vasurkoviktor',
    plastId: '',
    firstName: 'Viktor',
    lastName: 'Vasurko',
    childFirstNameUa: 'Віктор',
    childLastNameUa: 'Васюрко',
    dob: '09/27/2013',
    stupin: '',
    ulad: '',
    email: 'andruniv.l@gmail.com',
    phoneNumber: '6316446228',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '"801 N Clinton Ave',
    adressTown: '"',
    adressZipcode: 'Lindenhurst',
    adressState: '11757',
    parent1FirstName: 'NY',
    parent1LastName: 'Petro',
    parent1Email: 'Vasiurko',
    parent1PhoneNumber: '',
    parent2FirstName: '6316446250',
    parent2LastName: 'Roksolana',
    parent2Email: 'Vasiurko',
    parent2PhoneNumber: '',
  },
  {
    username: 'yurchakvictoria',
    plastId: '',
    firstName: 'Victoria',
    lastName: 'Yurchak',
    childFirstNameUa: 'Вікторія',
    childLastNameUa: 'Юрчак',
    dob: '02/16/2018',
    stupin: '',
    ulad: '',
    email: 'Dashavoytovych@hotmail.com',
    phoneNumber: '6315615527',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '187 Cadman Ave',
    adressTown: 'Babylon',
    adressZipcode: '11702',
    adressState: 'NY',
    parent1FirstName: 'Volodymyr',
    parent1LastName: 'Yurchak',
    parent1Email: '',
    parent1PhoneNumber: '6463308185',
    parent2FirstName: 'Darya',
    parent2LastName: 'Yurchak',
    parent2Email: 'Dashavoytovych@hotmail.com',
    parent2PhoneNumber: '6315615527',
  },
  {
    username: 'yurchakmaximilian',
    plastId: '',
    firstName: 'Maximilian',
    lastName: 'Yurchak',
    childFirstNameUa: 'Максим',
    childLastNameUa: 'Юрчак',
    dob: '11/17/2013',
    stupin: '',
    ulad: '',
    email: 'Dashavoytovych@hotmail.com',
    phoneNumber: '6315615527',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '187 Cadman Ave',
    adressTown: 'Babylon',
    adressZipcode: '11702',
    adressState: 'NY',
    parent1FirstName: 'Volodymyr',
    parent1LastName: 'Yurchak',
    parent1Email: '',
    parent1PhoneNumber: '6463308185',
    parent2FirstName: 'Darya',
    parent2LastName: 'Yurchak',
    parent2Email: 'Dashavoytovych@hotmail.com',
    parent2PhoneNumber: '6315615527',
  },
  {
    username: 'dubrovskyymark',
    plastId: '',
    firstName: 'Mark',
    lastName: 'Dubrovskyy',
    childFirstNameUa: 'Марко',
    childLastNameUa: 'Дубровський',
    dob: '3/7/2015',
    stupin: '',
    ulad: '',
    email: 'Slevus@gmail.com',
    phoneNumber: '2038324036',
    uaSchooGrade: '',
    usSchooGrade: '',
    adressStreet: '60 Seafield ln',
    adressTown: 'Bayshore',
    adressZipcode: '11706',
    adressState: 'NY',
    parent1FirstName: '',
    parent1LastName: '',
    parent1Email: '',
    parent1PhoneNumber: '',
    parent2FirstName: '',
    parent2LastName: '',
    parent2Email: '',
    parent2PhoneNumber: '',
  },
  { username: '' },
];
